---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-9.1

suites:
  - name: default
    run_list:
      - "recipe[cfssl::default]"
      - "recipe[cfssl::install]"
      - "recipe[cfssl::gen_ca]"
      - "recipe[cfssl::server]"
      # - "recipe[cfssl::client]"
      - "recipe[cfssl::gen_cert]"
    attributes:
