name             'cfssl'
maintainer       'Vegard Hansen'
maintainer_email 'vegard.x@gmail.com'
license          'GPLv2'
description      'Installs/Configures chef-cfssl'
long_description 'Installs/Configures chef-cfssl'
version          '0.1.0'
