name             'chef-cfssl'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef-cfssl'
long_description 'Installs/Configures chef-cfssl'
version          '0.1.0'
